name: gql_link_example
description: Demonstrates how to use the luciq_gql_link package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  luciq_flutter:
    path: ../../luciq_flutter
  luciq_gql_link:
    path: ../
  graphql_flutter: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  luciq_flutter:
    path: ../../luciq_flutter
  luciq_gql_link:
    path: ../

flutter:
  uses-material-design: true
