// Mocks generated by Mockito 5.4.4 from annotations
// in luciq_flutter/test/apm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:flutter/widgets.dart' as _i9;
import 'package:luciq_flutter/src/generated/apm.api.g.dart' as _i3;
import 'package:luciq_flutter/src/models/luciq_screen_render_data.dart' as _i2;
import 'package:luciq_flutter/src/utils/lcq_build_info.dart' as _i6;
import 'package:luciq_flutter/src/utils/lcq_date_time.dart' as _i5;
import 'package:luciq_flutter/src/utils/screen_rendering/luciq_screen_render_manager.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLuciqScreenRenderData_1 extends _i1.SmartFake
    implements _i2.LuciqScreenRenderData {
  _FakeLuciqScreenRenderData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApmHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockApmHostApi extends _i1.Mock implements _i3.ApmHostApi {
  MockApmHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setEnabled(bool? arg_isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setScreenLoadingEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenLoadingEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenLoadingEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setColdAppLaunchEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setColdAppLaunchEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAutoUITraceEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoUITraceEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startFlow,
          [arg_name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setFlowAttribute(
    String? arg_name,
    String? arg_key,
    String? arg_value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFlowAttribute,
          [
            arg_name,
            arg_key,
            arg_value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #endFlow,
          [arg_name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startUITrace(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startUITrace,
          [arg_name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endUITrace() => (super.noSuchMethod(
        Invocation.method(
          #endUITrace,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endAppLaunch() => (super.noSuchMethod(
        Invocation.method(
          #endAppLaunch,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> networkLogAndroid(Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #networkLogAndroid,
          [arg_data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startCpUiTrace(
    String? arg_screenName,
    int? arg_microTimeStamp,
    int? arg_traceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startCpUiTrace,
          [
            arg_screenName,
            arg_microTimeStamp,
            arg_traceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportScreenLoadingCP(
    int? arg_startTimeStampMicro,
    int? arg_durationMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenLoadingCP,
          [
            arg_startTimeStampMicro,
            arg_durationMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endScreenLoadingCP(
    int? arg_timeStampMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenLoadingCP,
          [
            arg_timeStampMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isEndScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEndScreenLoadingEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAutoUiTraceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAutoUiTraceEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isScreenRenderEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenRenderEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<double?>> getDeviceRefreshRateAndTolerance() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeviceRefreshRateAndTolerance,
          [],
        ),
        returnValue: _i4.Future<List<double?>>.value(<double?>[]),
      ) as _i4.Future<List<double?>>);

  @override
  _i4.Future<void> setScreenRenderEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenRenderEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endScreenRenderForAutoUiTrace(
          Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenRenderForAutoUiTrace,
          [arg_data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endScreenRenderForCustomUiTrace(
          Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenRenderForCustomUiTrace,
          [arg_data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LCQDateTime].
///
/// See the documentation for Mockito's code generation for more information.
class MockLCQDateTime extends _i1.Mock implements _i5.LCQDateTime {
  MockLCQDateTime() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}

/// A class which mocks [LCQBuildInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLCQBuildInfo extends _i1.Mock implements _i6.LCQBuildInfo {
  MockLCQBuildInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
      ) as bool);

  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
      ) as bool);

  @override
  String get operatingSystem => (super.noSuchMethod(
        Invocation.getter(#operatingSystem),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#operatingSystem),
        ),
      ) as String);

  @override
  bool get isReleaseMode => (super.noSuchMethod(
        Invocation.getter(#isReleaseMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isDebugMode => (super.noSuchMethod(
        Invocation.getter(#isDebugMode),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [LuciqScreenRenderManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuciqScreenRenderManager extends _i1.Mock
    implements _i8.LuciqScreenRenderManager {
  MockLuciqScreenRenderManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get screenRenderEnabled => (super.noSuchMethod(
        Invocation.getter(#screenRenderEnabled),
        returnValue: false,
      ) as bool);

  @override
  set screenRenderEnabled(bool? _screenRenderEnabled) => super.noSuchMethod(
        Invocation.setter(
          #screenRenderEnabled,
          _screenRenderEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.LuciqScreenRenderData get screenRenderForAutoUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForAutoUiTrace),
        returnValue: _FakeLuciqScreenRenderData_1(
          this,
          Invocation.getter(#screenRenderForAutoUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i2.LuciqScreenRenderData get screenRenderForCustomUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForCustomUiTrace),
        returnValue: _FakeLuciqScreenRenderData_1(
          this,
          Invocation.getter(#screenRenderForCustomUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i4.Future<void> init(_i9.WidgetsBinding? widgetBinding) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [widgetBinding],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void analyzeFrameTiming(_i10.FrameTiming? frameTiming) => super.noSuchMethod(
        Invocation.method(
          #analyzeFrameTiming,
          [frameTiming],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startScreenRenderCollectorForTraceId(
    int? traceId, [
    _i8.UiTraceType? type = _i8.UiTraceType.auto,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #startScreenRenderCollectorForTraceId,
          [
            traceId,
            type,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endScreenRenderCollector(
          [_i8.UiTraceType? type = _i8.UiTraceType.auto]) =>
      super.noSuchMethod(
        Invocation.method(
          #endScreenRenderCollector,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncCollectedScreenRenderingData() => super.noSuchMethod(
        Invocation.method(
          #syncCollectedScreenRenderingData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> checkForScreenRenderInitialization(
          bool? isScreenRenderEnabledFromBackend) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForScreenRenderInitialization,
          [isScreenRenderEnabledFromBackend],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFrameData(_i2.LuciqScreenRenderData? data) => super.noSuchMethod(
        Invocation.method(
          #setFrameData,
          [data],
        ),
        returnValueForMissingStub: null,
      );
}
