name: luciq_gql_link
description:
  This package is an add on to luciq_flutter. It intercepts any GraphQL
  operations performed with the gql package and sends them to the report
  that will be sent to the dashboard.
version: 1.0.0
homepage: https://github.com/luciqai/luciq-flutter-sdk#readme
repository: https://github.com/luciqai/luciq-flutter-sdk/tree/master/packages/luciq_gql_link

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gql: '>=0.13.0 <2.0.0'
  gql_exec: '>=0.4.0 <2.0.0'
  gql_http_link: '>=0.4.0 <2.0.0'
  gql_link: '>=0.4.0 <2.0.0'
  luciq_flutter: '>=19.0.0 <20.0.0'

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  mockito: ^5.0.10
  pana: ^0.21.0

flutter:
