// Mocks generated by Mockito 5.4.4 from annotations
// in luciq_flutter/test/utils/canonical_log_shape_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:luciq_flutter/luciq_flutter.dart' as _i3;
import 'package:luciq_flutter/src/utils/luciq_logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LuciqLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuciqLogger extends _i1.Mock implements _i2.LuciqLogger {
  MockLuciqLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.LogLevel get logLevel => (super.noSuchMethod(
        Invocation.getter(#logLevel),
        returnValue: _i3.LogLevel.none,
      ) as _i3.LogLevel);

  @override
  set logLevel(_i3.LogLevel? _logLevel) => super.noSuchMethod(
        Invocation.setter(
          #logLevel,
          _logLevel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isDebugEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isDebugEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void log(
    String? message, {
    required _i3.LogLevel? level,
    String? tag = r'',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #tag: tag,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void e(
    String? message, {
    String? tag = r'',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
          {#tag: tag},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void d(
    String? message, {
    String? tag = r'',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #d,
          [message],
          {#tag: tag},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void v(
    String? message, {
    String? tag = r'',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v,
          [message],
          {#tag: tag},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void w(
    String? message, {
    String? tag = r'',
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #w,
          [message],
          {#tag: tag},
        ),
        returnValueForMissingStub: null,
      );
}
