// Mocks generated by Mockito 5.4.4 from annotations
// in luciq_flutter/test/utils/luciq_navigator_observer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i12;

import 'package:flutter/widgets.dart' as _i11;
import 'package:luciq_flutter/luciq_flutter.dart' as _i6;
import 'package:luciq_flutter/src/generated/luciq.api.g.dart' as _i3;
import 'package:luciq_flutter/src/models/luciq_screen_render_data.dart' as _i2;
import 'package:luciq_flutter/src/utils/screen_loading/screen_loading_trace.dart'
    as _i8;
import 'package:luciq_flutter/src/utils/screen_loading/ui_trace.dart' as _i7;
import 'package:luciq_flutter/src/utils/screen_rendering/luciq_screen_render_manager.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLuciqScreenRenderData_0 extends _i1.SmartFake
    implements _i2.LuciqScreenRenderData {
  _FakeLuciqScreenRenderData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LuciqHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuciqHostApi extends _i1.Mock implements _i3.LuciqHostApi {
  MockLuciqHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setEnabled(bool? arg_isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isBuilt() => (super.noSuchMethod(
        Invocation.method(
          #isBuilt,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> init(
    String? arg_token,
    List<String?>? arg_invocationEvents,
    String? arg_debugLogsLevel,
    String? arg_appVariant,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [
            arg_token,
            arg_invocationEvents,
            arg_debugLogsLevel,
            arg_appVariant,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enableAutoMasking(List<String?>? arg_autoMasking) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableAutoMasking,
          [arg_autoMasking],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> show() => (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showWelcomeMessageWithMode(String? arg_mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #showWelcomeMessageWithMode,
          [arg_mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> identifyUser(
    String? arg_email,
    String? arg_name,
    String? arg_userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #identifyUser,
          [
            arg_email,
            arg_name,
            arg_userId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserData(String? arg_data) => (super.noSuchMethod(
        Invocation.method(
          #setUserData,
          [arg_data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setAppVariant(String? arg_appVariant) => (super.noSuchMethod(
        Invocation.method(
          #setAppVariant,
          [arg_appVariant],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logUserEvent(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #logUserEvent,
          [arg_name],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setEnableUserSteps(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEnableUserSteps,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logUserSteps(
    String? arg_gestureType,
    String? arg_message,
    String? arg_viewName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logUserSteps,
          [
            arg_gestureType,
            arg_message,
            arg_viewName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setLocale(String? arg_locale) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [arg_locale],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setColorTheme(String? arg_theme) => (super.noSuchMethod(
        Invocation.method(
          #setColorTheme,
          [arg_theme],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setWelcomeMessageMode(String? arg_mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWelcomeMessageMode,
          [arg_mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setSessionProfilerEnabled(bool? arg_enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSessionProfilerEnabled,
          [arg_enabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setValueForStringWithKey(
    String? arg_value,
    String? arg_key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setValueForStringWithKey,
          [
            arg_value,
            arg_key,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> appendTags(List<String?>? arg_tags) => (super.noSuchMethod(
        Invocation.method(
          #appendTags,
          [arg_tags],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetTags() => (super.noSuchMethod(
        Invocation.method(
          #resetTags,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String?>?> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: _i4.Future<List<String?>?>.value(),
      ) as _i4.Future<List<String?>?>);

  @override
  _i4.Future<void> addFeatureFlags(
          Map<String?, String?>? arg_featureFlagsMap) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFeatureFlags,
          [arg_featureFlagsMap],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFeatureFlags(List<String?>? arg_featureFlags) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFeatureFlags,
          [arg_featureFlags],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeAllFeatureFlags() => (super.noSuchMethod(
        Invocation.method(
          #removeAllFeatureFlags,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserAttribute(
    String? arg_value,
    String? arg_key,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserAttribute,
          [
            arg_value,
            arg_key,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeUserAttribute(String? arg_key) => (super.noSuchMethod(
        Invocation.method(
          #removeUserAttribute,
          [arg_key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserAttributeForKey(String? arg_key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAttributeForKey,
          [arg_key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<Map<String?, String?>?> getUserAttributes() => (super.noSuchMethod(
        Invocation.method(
          #getUserAttributes,
          [],
        ),
        returnValue: _i4.Future<Map<String?, String?>?>.value(),
      ) as _i4.Future<Map<String?, String?>?>);

  @override
  _i4.Future<void> setReproStepsConfig(
    String? arg_bugMode,
    String? arg_crashMode,
    String? arg_sessionReplayMode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReproStepsConfig,
          [
            arg_bugMode,
            arg_crashMode,
            arg_sessionReplayMode,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportScreenChange(String? arg_screenName) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenChange,
          [arg_screenName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setCustomBrandingImage(
    String? arg_light,
    String? arg_dark,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomBrandingImage,
          [
            arg_light,
            arg_dark,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setFont(String? arg_font) => (super.noSuchMethod(
        Invocation.method(
          #setFont,
          [arg_font],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addFileAttachmentWithURL(
    String? arg_filePath,
    String? arg_fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFileAttachmentWithURL,
          [
            arg_filePath,
            arg_fileName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addFileAttachmentWithData(
    _i5.Uint8List? arg_data,
    String? arg_fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFileAttachmentWithData,
          [
            arg_data,
            arg_fileName,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearFileAttachments() => (super.noSuchMethod(
        Invocation.method(
          #clearFileAttachments,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> networkLog(Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #networkLog,
          [arg_data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> registerFeatureFlagChangeListener() => (super.noSuchMethod(
        Invocation.method(
          #registerFeatureFlagChangeListener,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String?, bool?>> isW3CFeatureFlagsEnabled() =>
      (super.noSuchMethod(
        Invocation.method(
          #isW3CFeatureFlagsEnabled,
          [],
        ),
        returnValue: _i4.Future<Map<String?, bool?>>.value(<String?, bool?>{}),
      ) as _i4.Future<Map<String?, bool?>>);

  @override
  _i4.Future<void> willRedirectToStore() => (super.noSuchMethod(
        Invocation.method(
          #willRedirectToStore,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setNetworkLogBodyEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkLogBodyEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<double?> getNetworkBodyMaxSize() => (super.noSuchMethod(
        Invocation.method(
          #getNetworkBodyMaxSize,
          [],
        ),
        returnValue: _i4.Future<double?>.value(),
      ) as _i4.Future<double?>);

  @override
  _i4.Future<void> setTheme(Map<String?, Object?>? arg_themeConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTheme,
          [arg_themeConfig],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setFullscreen(bool? arg_isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setFullscreen,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setNetworkAutoMaskingEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNetworkAutoMaskingEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ScreenLoadingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockScreenLoadingManager extends _i1.Mock
    implements _i6.ScreenLoadingManager {
  MockScreenLoadingManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUiTrace(_i7.UiTrace? _currentUiTrace) => super.noSuchMethod(
        Invocation.setter(
          #currentUiTrace,
          _currentUiTrace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentScreenLoadingTrace(
          _i8.ScreenLoadingTrace? _currentScreenLoadingTrace) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentScreenLoadingTrace,
          _currentScreenLoadingTrace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.ScreenLoadingTrace> get prematurelyEndedTraces =>
      (super.noSuchMethod(
        Invocation.getter(#prematurelyEndedTraces),
        returnValue: <_i8.ScreenLoadingTrace>[],
      ) as List<_i8.ScreenLoadingTrace>);

  @override
  void resetDidStartScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidStartScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetDidReportScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidReportScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetDidExtendScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidExtendScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String sanitizeScreenName(String? screenName) => (super.noSuchMethod(
        Invocation.method(
          #sanitizeScreenName,
          [screenName],
        ),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.method(
            #sanitizeScreenName,
            [screenName],
          ),
        ),
      ) as String);

  @override
  _i4.Future<int?> startUiTrace(
    String? screenName, [
    String? matchingScreenName,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #startUiTrace,
          [
            screenName,
            matchingScreenName,
          ],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<void> startScreenLoadingTrace(_i8.ScreenLoadingTrace? trace) =>
      (super.noSuchMethod(
        Invocation.method(
          #startScreenLoadingTrace,
          [trace],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportScreenLoading(_i8.ScreenLoadingTrace? trace) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenLoading,
          [trace],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endScreenLoading() => (super.noSuchMethod(
        Invocation.method(
          #endScreenLoading,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LuciqScreenRenderManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuciqScreenRenderManager extends _i1.Mock
    implements _i10.LuciqScreenRenderManager {
  MockLuciqScreenRenderManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get screenRenderEnabled => (super.noSuchMethod(
        Invocation.getter(#screenRenderEnabled),
        returnValue: false,
      ) as bool);

  @override
  set screenRenderEnabled(bool? _screenRenderEnabled) => super.noSuchMethod(
        Invocation.setter(
          #screenRenderEnabled,
          _screenRenderEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.LuciqScreenRenderData get screenRenderForAutoUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForAutoUiTrace),
        returnValue: _FakeLuciqScreenRenderData_0(
          this,
          Invocation.getter(#screenRenderForAutoUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i2.LuciqScreenRenderData get screenRenderForCustomUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForCustomUiTrace),
        returnValue: _FakeLuciqScreenRenderData_0(
          this,
          Invocation.getter(#screenRenderForCustomUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i4.Future<void> init(_i11.WidgetsBinding? widgetBinding) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [widgetBinding],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void analyzeFrameTiming(_i12.FrameTiming? frameTiming) => super.noSuchMethod(
        Invocation.method(
          #analyzeFrameTiming,
          [frameTiming],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startScreenRenderCollectorForTraceId(
    int? traceId, [
    _i10.UiTraceType? type = _i10.UiTraceType.auto,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #startScreenRenderCollectorForTraceId,
          [
            traceId,
            type,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endScreenRenderCollector(
          [_i10.UiTraceType? type = _i10.UiTraceType.auto]) =>
      super.noSuchMethod(
        Invocation.method(
          #endScreenRenderCollector,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncCollectedScreenRenderingData() => super.noSuchMethod(
        Invocation.method(
          #syncCollectedScreenRenderingData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> checkForScreenRenderInitialization(
          bool? isScreenRenderEnabledFromBackend) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForScreenRenderInitialization,
          [isScreenRenderEnabledFromBackend],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFrameData(_i2.LuciqScreenRenderData? data) => super.noSuchMethod(
        Invocation.method(
          #setFrameData,
          [data],
        ),
        returnValueForMissingStub: null,
      );
}
