// Mocks generated by Mockito 5.4.4 from annotations
// in luciq_flutter/test/utils/screen_render/luciq_widget_binding_observer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:flutter/widgets.dart' as _i6;
import 'package:luciq_flutter/luciq_flutter.dart' as _i8;
import 'package:luciq_flutter/src/generated/apm.api.g.dart' as _i12;
import 'package:luciq_flutter/src/models/luciq_screen_render_data.dart' as _i2;
import 'package:luciq_flutter/src/utils/lcq_build_info.dart' as _i13;
import 'package:luciq_flutter/src/utils/screen_loading/screen_loading_trace.dart'
    as _i9;
import 'package:luciq_flutter/src/utils/screen_loading/ui_trace.dart' as _i3;
import 'package:luciq_flutter/src/utils/screen_name_masker.dart' as _i11;
import 'package:luciq_flutter/src/utils/screen_rendering/luciq_screen_render_manager.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLuciqScreenRenderData_0 extends _i1.SmartFake
    implements _i2.LuciqScreenRenderData {
  _FakeLuciqScreenRenderData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUiTrace_1 extends _i1.SmartFake implements _i3.UiTrace {
  _FakeUiTrace_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LuciqScreenRenderManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLuciqScreenRenderManager extends _i1.Mock
    implements _i4.LuciqScreenRenderManager {
  MockLuciqScreenRenderManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get screenRenderEnabled => (super.noSuchMethod(
        Invocation.getter(#screenRenderEnabled),
        returnValue: false,
      ) as bool);

  @override
  set screenRenderEnabled(bool? _screenRenderEnabled) => super.noSuchMethod(
        Invocation.setter(
          #screenRenderEnabled,
          _screenRenderEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.LuciqScreenRenderData get screenRenderForAutoUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForAutoUiTrace),
        returnValue: _FakeLuciqScreenRenderData_0(
          this,
          Invocation.getter(#screenRenderForAutoUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i2.LuciqScreenRenderData get screenRenderForCustomUiTrace =>
      (super.noSuchMethod(
        Invocation.getter(#screenRenderForCustomUiTrace),
        returnValue: _FakeLuciqScreenRenderData_0(
          this,
          Invocation.getter(#screenRenderForCustomUiTrace),
        ),
      ) as _i2.LuciqScreenRenderData);

  @override
  _i5.Future<void> init(_i6.WidgetsBinding? widgetBinding) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [widgetBinding],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void analyzeFrameTiming(_i7.FrameTiming? frameTiming) => super.noSuchMethod(
        Invocation.method(
          #analyzeFrameTiming,
          [frameTiming],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startScreenRenderCollectorForTraceId(
    int? traceId, [
    _i4.UiTraceType? type = _i4.UiTraceType.auto,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #startScreenRenderCollectorForTraceId,
          [
            traceId,
            type,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endScreenRenderCollector(
          [_i4.UiTraceType? type = _i4.UiTraceType.auto]) =>
      super.noSuchMethod(
        Invocation.method(
          #endScreenRenderCollector,
          [type],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void syncCollectedScreenRenderingData() => super.noSuchMethod(
        Invocation.method(
          #syncCollectedScreenRenderingData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> checkForScreenRenderInitialization(
          bool? isScreenRenderEnabledFromBackend) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForScreenRenderInitialization,
          [isScreenRenderEnabledFromBackend],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFrameData(_i2.LuciqScreenRenderData? data) => super.noSuchMethod(
        Invocation.method(
          #setFrameData,
          [data],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ScreenLoadingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockScreenLoadingManager extends _i1.Mock
    implements _i8.ScreenLoadingManager {
  MockScreenLoadingManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set currentUiTrace(_i3.UiTrace? _currentUiTrace) => super.noSuchMethod(
        Invocation.setter(
          #currentUiTrace,
          _currentUiTrace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentScreenLoadingTrace(
          _i9.ScreenLoadingTrace? _currentScreenLoadingTrace) =>
      super.noSuchMethod(
        Invocation.setter(
          #currentScreenLoadingTrace,
          _currentScreenLoadingTrace,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.ScreenLoadingTrace> get prematurelyEndedTraces =>
      (super.noSuchMethod(
        Invocation.getter(#prematurelyEndedTraces),
        returnValue: <_i9.ScreenLoadingTrace>[],
      ) as List<_i9.ScreenLoadingTrace>);

  @override
  void resetDidStartScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidStartScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetDidReportScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidReportScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetDidExtendScreenLoading() => super.noSuchMethod(
        Invocation.method(
          #resetDidExtendScreenLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String sanitizeScreenName(String? screenName) => (super.noSuchMethod(
        Invocation.method(
          #sanitizeScreenName,
          [screenName],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #sanitizeScreenName,
            [screenName],
          ),
        ),
      ) as String);

  @override
  _i5.Future<int?> startUiTrace(
    String? screenName, [
    String? matchingScreenName,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #startUiTrace,
          [
            screenName,
            matchingScreenName,
          ],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> startScreenLoadingTrace(_i9.ScreenLoadingTrace? trace) =>
      (super.noSuchMethod(
        Invocation.method(
          #startScreenLoadingTrace,
          [trace],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reportScreenLoading(_i9.ScreenLoadingTrace? trace) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenLoading,
          [trace],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endScreenLoading() => (super.noSuchMethod(
        Invocation.method(
          #endScreenLoading,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ScreenNameMasker].
///
/// See the documentation for Mockito's code generation for more information.
class MockScreenNameMasker extends _i1.Mock implements _i11.ScreenNameMasker {
  MockScreenNameMasker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setMaskingCallback(_i8.ScreenNameMaskingCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setMaskingCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String mask(String? screen) => (super.noSuchMethod(
        Invocation.method(
          #mask,
          [screen],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #mask,
            [screen],
          ),
        ),
      ) as String);
}

/// A class which mocks [UiTrace].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiTrace extends _i1.Mock implements _i3.UiTrace {
  MockUiTrace() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get screenName => (super.noSuchMethod(
        Invocation.getter(#screenName),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#screenName),
        ),
      ) as String);

  @override
  int get traceId => (super.noSuchMethod(
        Invocation.getter(#traceId),
        returnValue: 0,
      ) as int);

  @override
  bool get didStartScreenLoading => (super.noSuchMethod(
        Invocation.getter(#didStartScreenLoading),
        returnValue: false,
      ) as bool);

  @override
  set didStartScreenLoading(bool? _didStartScreenLoading) => super.noSuchMethod(
        Invocation.setter(
          #didStartScreenLoading,
          _didStartScreenLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get didReportScreenLoading => (super.noSuchMethod(
        Invocation.getter(#didReportScreenLoading),
        returnValue: false,
      ) as bool);

  @override
  set didReportScreenLoading(bool? _didReportScreenLoading) =>
      super.noSuchMethod(
        Invocation.setter(
          #didReportScreenLoading,
          _didReportScreenLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get didExtendScreenLoading => (super.noSuchMethod(
        Invocation.getter(#didExtendScreenLoading),
        returnValue: false,
      ) as bool);

  @override
  set didExtendScreenLoading(bool? _didExtendScreenLoading) =>
      super.noSuchMethod(
        Invocation.setter(
          #didExtendScreenLoading,
          _didExtendScreenLoading,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.UiTrace copyWith({
    String? screenName,
    String? matchingScreenName,
    int? traceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #screenName: screenName,
            #matchingScreenName: matchingScreenName,
            #traceId: traceId,
          },
        ),
        returnValue: _FakeUiTrace_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #screenName: screenName,
              #matchingScreenName: matchingScreenName,
              #traceId: traceId,
            },
          ),
        ),
      ) as _i3.UiTrace);

  @override
  bool matches(String? routePath) => (super.noSuchMethod(
        Invocation.method(
          #matches,
          [routePath],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ApmHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockApmHostApi extends _i1.Mock implements _i12.ApmHostApi {
  MockApmHostApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setEnabled(bool? arg_isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setScreenLoadingEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenLoadingEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenLoadingEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setColdAppLaunchEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setColdAppLaunchEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setAutoUITraceEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoUITraceEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startFlow,
          [arg_name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFlowAttribute(
    String? arg_name,
    String? arg_key,
    String? arg_value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFlowAttribute,
          [
            arg_name,
            arg_key,
            arg_value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endFlow(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #endFlow,
          [arg_name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startUITrace(String? arg_name) => (super.noSuchMethod(
        Invocation.method(
          #startUITrace,
          [arg_name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endUITrace() => (super.noSuchMethod(
        Invocation.method(
          #endUITrace,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endAppLaunch() => (super.noSuchMethod(
        Invocation.method(
          #endAppLaunch,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> networkLogAndroid(Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #networkLogAndroid,
          [arg_data],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startCpUiTrace(
    String? arg_screenName,
    int? arg_microTimeStamp,
    int? arg_traceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startCpUiTrace,
          [
            arg_screenName,
            arg_microTimeStamp,
            arg_traceId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reportScreenLoadingCP(
    int? arg_startTimeStampMicro,
    int? arg_durationMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportScreenLoadingCP,
          [
            arg_startTimeStampMicro,
            arg_durationMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endScreenLoadingCP(
    int? arg_timeStampMicro,
    int? arg_uiTraceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenLoadingCP,
          [
            arg_timeStampMicro,
            arg_uiTraceId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isEndScreenLoadingEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isEndScreenLoadingEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isAutoUiTraceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAutoUiTraceEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isScreenRenderEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenRenderEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<double?>> getDeviceRefreshRateAndTolerance() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeviceRefreshRateAndTolerance,
          [],
        ),
        returnValue: _i5.Future<List<double?>>.value(<double?>[]),
      ) as _i5.Future<List<double?>>);

  @override
  _i5.Future<void> setScreenRenderEnabled(bool? arg_isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenRenderEnabled,
          [arg_isEnabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endScreenRenderForAutoUiTrace(
          Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenRenderForAutoUiTrace,
          [arg_data],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> endScreenRenderForCustomUiTrace(
          Map<String?, Object?>? arg_data) =>
      (super.noSuchMethod(
        Invocation.method(
          #endScreenRenderForCustomUiTrace,
          [arg_data],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LCQBuildInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLCQBuildInfo extends _i1.Mock implements _i13.LCQBuildInfo {
  MockLCQBuildInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
      ) as bool);

  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
      ) as bool);

  @override
  String get operatingSystem => (super.noSuchMethod(
        Invocation.getter(#operatingSystem),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#operatingSystem),
        ),
      ) as String);

  @override
  bool get isReleaseMode => (super.noSuchMethod(
        Invocation.getter(#isReleaseMode),
        returnValue: false,
      ) as bool);

  @override
  bool get isDebugMode => (super.noSuchMethod(
        Invocation.getter(#isDebugMode),
        returnValue: false,
      ) as bool);
}
